export interface ScholarQuestion {
  id: number;
  category: "verbal" | "quant";
  text: string;
  options: string[];
  correctIndex: number;
}

// ── 100 Verbal Questions (IDs 1-100) ─────────────────────────────────────────

export const VERBAL_QUESTIONS: ScholarQuestion[] = [
  { id: 1, category: "verbal", text: "PERSPICACIOUS most nearly means:", options: ["Shrewd and discerning", "Easily frightened", "Loudly opinionated", "Casually indifferent"], correctIndex: 0 },
  { id: 2, category: "verbal", text: "INIMICAL : HOSTILE :: SANGUINE : ___", options: ["Pessimistic", "Optimistic", "Secretive", "Temperamental"], correctIndex: 1 },
  { id: 3, category: "verbal", text: "Choose the ODD one out: CRIMSON, SCARLET, VERMILLION, COBALT", options: ["Crimson", "Scarlet", "Vermillion", "Cobalt"], correctIndex: 3 },
  { id: 4, category: "verbal", text: "LACONIC most nearly means the OPPOSITE of:", options: ["Verbose", "Quiet", "Deliberate", "Energetic"], correctIndex: 0 },
  { id: 5, category: "verbal", text: "His argument was so ___ that even the skeptics were fully convinced.", options: ["Specious", "Verbose", "Cogent", "Insipid"], correctIndex: 2 },
  { id: 6, category: "verbal", text: "EPHEMERAL most nearly means:", options: ["Eternal", "Transient", "Heavenly", "Massive"], correctIndex: 1 },
  { id: 7, category: "verbal", text: "The judge's ruling was PERSPICUOUS. This means the ruling was:", options: ["Foolish and impulsive", "Clearly understandable", "Highly profitable", "Widely unpopular"], correctIndex: 1 },
  { id: 8, category: "verbal", text: "All Tigers are Felines. All Felines are Carnivores. Which conclusion MUST be true?", options: ["All Carnivores are Tigers", "Some Tigers are not Carnivores", "All Tigers are Carnivores", "No Tiger is a Feline"], correctIndex: 2 },
  { id: 9, category: "verbal", text: "AMELIORATE most nearly means:", options: ["Worsen gradually", "Improve or correct", "Combine forces", "Memorise completely"], correctIndex: 1 },
  { id: 10, category: "verbal", text: "OSTENTATIOUS behaviour is best described as:", options: ["Quiet and thoughtful", "Showy and pretentious", "Kind and compassionate", "Systematic and efficient"], correctIndex: 1 },
  { id: 11, category: "verbal", text: "Playwright : Play :: Sculptor : ___", options: ["Stone", "Gallery", "Chisel", "Statue"], correctIndex: 3 },
  { id: 12, category: "verbal", text: "The senator's speech was full of PLATITUDES. This means the speech was:", options: ["Intellectually complex", "Full of trite, overused remarks", "Brief and decisive", "Challenging to existing policies"], correctIndex: 1 },
  { id: 13, category: "verbal", text: "VITUPERATE most nearly means:", options: ["To praise lavishly", "To investigate carefully", "To criticise harshly", "To ignore pointedly"], correctIndex: 2 },
  { id: 14, category: "verbal", text: "OBFUSCATE most nearly means:", options: ["To clarify precisely", "To render obscure or unclear", "To simplify thoroughly", "To verify independently"], correctIndex: 1 },
  { id: 15, category: "verbal", text: "LOQUACIOUS : TALKER :: PARSIMONIOUS : ___", options: ["Spendthrift", "Miser", "Banker", "Philanthropist"], correctIndex: 1 },
  { id: 16, category: "verbal", text: "DEBILITATE most nearly means:", options: ["To strengthen gradually", "To inspire deeply", "To weaken or impair", "To motivate effectively"], correctIndex: 2 },
  { id: 17, category: "verbal", text: "Which sentence is grammatically correct?", options: ["Neither he nor his friends was present.", "Neither he nor his friends were present.", "Neither he or his friends were present.", "Neither his friends or he was present."], correctIndex: 1 },
  { id: 18, category: "verbal", text: "CIRCUMSPECT behaviour suggests someone who is:", options: ["Reckless and spontaneous", "Wary and attentive to all circumstances", "Outgoing and sociable", "Stubborn and unchanging"], correctIndex: 1 },
  { id: 19, category: "verbal", text: "MAGNANIMOUS most nearly means the OPPOSITE of:", options: ["Generous", "Heroic", "Petty and mean-spirited", "Thoughtful"], correctIndex: 2 },
  { id: 20, category: "verbal", text: "A study concludes: 'Students who eat breakfast perform better in exams.' The STRONGEST challenge to this conclusion is:", options: ["Some students who skip breakfast also perform well.", "The study did not control for students' sleep patterns, study hours, and prior academic ability.", "Breakfast is expensive for low-income families.", "The study only covered one school."], correctIndex: 1 },
  { id: 21, category: "verbal", text: "AMELIORATE : IMPROVE :: EXACERBATE : ___", options: ["Fix", "Worsen", "Replace", "Delay"], correctIndex: 1 },
  { id: 22, category: "verbal", text: "VOLUBLE most nearly means:", options: ["Easily moved or rolled", "Talkative and fluent in speech", "Loud and aggressive", "Slow and deliberate"], correctIndex: 1 },
  { id: 23, category: "verbal", text: "LAMENT most nearly means:", options: ["To celebrate enthusiastically", "To express grief or sorrow", "To argue persistently", "To recall with pleasure"], correctIndex: 1 },
  { id: 24, category: "verbal", text: "CONUNDRUM most nearly means:", options: ["A simple task", "A clear solution", "A confusing problem or question", "A lengthy process"], correctIndex: 2 },
  { id: 25, category: "verbal", text: "ADMONISH most nearly means:", options: ["To praise warmly", "To warn or reprimand gently", "To reward generously", "To ignore completely"], correctIndex: 1 },
  { id: 26, category: "verbal", text: "TENACITY most nearly means:", options: ["Willingness to give up easily", "Persistent determination", "Physical flexibility", "Emotional sensitivity"], correctIndex: 1 },
  { id: 27, category: "verbal", text: "Which sentence is grammatically correct?", options: ["He don't know the answer.", "They doesn't have any food left.", "She hasn't finished her assignment.", "We was waiting for an hour."], correctIndex: 2 },
  { id: 28, category: "verbal", text: "CONTEMPLATE most nearly means:", options: ["To act without thinking", "To think carefully about something", "To ignore completely", "To speak loudly about"], correctIndex: 1 },
  { id: 29, category: "verbal", text: "METICULOUS most nearly means:", options: ["Careless and hasty", "Very careful and precise", "Loud and aggressive", "Modest and quiet"], correctIndex: 1 },
  { id: 30, category: "verbal", text: "AFFLUENT most nearly means:", options: ["Extremely poor", "Working very hard", "Very wealthy", "Well-educated"], correctIndex: 2 },
  { id: 31, category: "verbal", text: "SPORADIC most nearly means:", options: ["Occurring regularly and predictably", "Happening at irregular intervals", "Continuous and uninterrupted", "Planned and deliberate"], correctIndex: 1 },
  { id: 32, category: "verbal", text: "The teacher commended the student for her ___; she had submitted every assignment on time all year.", options: ["Negligence", "Truancy", "Diligence", "Indolence"], correctIndex: 2 },
  { id: 33, category: "verbal", text: "RHETORIC most nearly means:", options: ["Language designed to persuade", "Truthful and honest speech", "A form of written poetry", "Official legal language"], correctIndex: 0 },
  { id: 34, category: "verbal", text: "STAGNANT most nearly means:", options: ["Moving rapidly", "Growing steadily", "Not flowing or developing", "Loudly protesting"], correctIndex: 2 },
  { id: 35, category: "verbal", text: "PERNICIOUS most nearly means:", options: ["Beneficial and helpful", "Having a harmful or destructive effect", "Extremely beautiful", "Lacking importance"], correctIndex: 1 },
  { id: 36, category: "verbal", text: "FRIVOLOUS most nearly means:", options: ["Serious and important", "Not having any serious purpose", "Deeply thoughtful", "Practically useful"], correctIndex: 1 },
  { id: 37, category: "verbal", text: "The professor gave his ___ approval — acknowledging the research while noting its limitations.", options: ["Wholehearted", "Qualified", "Absolute", "Enthusiastic"], correctIndex: 1 },
  { id: 38, category: "verbal", text: "LUCID most nearly means:", options: ["Confusing and complex", "Clear and easy to understand", "Secretive and hidden", "Loud and forceful"], correctIndex: 1 },
  { id: 39, category: "verbal", text: "COERCE most nearly means:", options: ["To persuade gently", "To force someone to do something", "To praise someone's efforts", "To help someone in difficulty"], correctIndex: 1 },
  { id: 40, category: "verbal", text: "STOIC most nearly means:", options: ["Easily upset by discomfort", "Enduring hardship without complaint", "Overly dramatic in expression", "Quick to seek help"], correctIndex: 1 },
  { id: 41, category: "verbal", text: "EQUIVOCATE most nearly means:", options: ["To speak with absolute certainty", "To use ambiguous language to avoid commitment", "To argue aggressively", "To remain completely silent"], correctIndex: 1 },
  { id: 42, category: "verbal", text: "TORPID most nearly means:", options: ["Energetic and enthusiastic", "Sluggish and inactive", "Quick to anger", "Deeply focused"], correctIndex: 1 },
  { id: 43, category: "verbal", text: "VINDICATE most nearly means:", options: ["To accuse formally", "To punish severely", "To clear of blame or suspicion", "To delay indefinitely"], correctIndex: 2 },
  { id: 44, category: "verbal", text: "CARTOGRAPHER : MAPS :: NUMISMATIST : ___", options: ["Stamps", "Coins", "Antiques", "Paintings"], correctIndex: 1 },
  { id: 45, category: "verbal", text: "The manager's decision was IMPETUOUS, meaning it was:", options: ["Carefully considered", "Hasty and impulsive", "Delayed unnecessarily", "Widely applauded"], correctIndex: 1 },
  { id: 46, category: "verbal", text: "RECALCITRANT most nearly means:", options: ["Eagerly cooperative", "Stubbornly defiant of authority", "Deeply remorseful", "Easily distracted"], correctIndex: 1 },
  { id: 47, category: "verbal", text: "No Oaks are Shrubs. All Bonsais are Oaks. Which conclusion MUST follow?", options: ["Some Bonsais are Shrubs", "No Bonsais are Shrubs", "All Shrubs are Oaks", "Some Oaks are Bonsais"], correctIndex: 1 },
  { id: 48, category: "verbal", text: "PROSAIC most nearly means:", options: ["Highly imaginative", "Technically complex", "Ordinary and dull", "Elegantly poetic"], correctIndex: 2 },
  { id: 49, category: "verbal", text: "The scientist's data ___ her hypothesis, leaving it completely unsupported.", options: ["Corroborated", "Vindicated", "Refuted", "Amplified"], correctIndex: 2 },
  { id: 50, category: "verbal", text: "AUSPICIOUS most nearly means the OPPOSITE of:", options: ["Promising", "Ill-omened", "Successful", "Celebrated"], correctIndex: 1 },
  { id: 51, category: "verbal", text: "PHLEGMATIC most nearly means:", options: ["Easily excited", "Calm and unemotional", "Prone to anger", "Overly talkative"], correctIndex: 1 },
  { id: 52, category: "verbal", text: "ENERVATE most nearly means:", options: ["To energise completely", "To drain of strength or vitality", "To encourage boldly", "To reorganise efficiently"], correctIndex: 1 },
  { id: 53, category: "verbal", text: "All politicians are public servants. Some public servants are corrupt. Which conclusion is VALID?", options: ["All politicians are corrupt.", "Some politicians may be corrupt.", "No politicians are corrupt.", "All public servants are politicians."], correctIndex: 1 },
  { id: 54, category: "verbal", text: "GARRULOUS : SILENT :: MISERLY : ___", options: ["Wealthy", "Generous", "Frugal", "Envious"], correctIndex: 1 },
  { id: 55, category: "verbal", text: "Despite years of ACRIMONY, the two parties finally reached an agreement. ACRIMONY means:", options: ["Patient negotiation", "Bitter hostility", "Mutual admiration", "Formal ceremony"], correctIndex: 1 },
  { id: 56, category: "verbal", text: "TACITURN most nearly means:", options: ["Boastful and loud", "Reserved and saying little", "Friendly and outgoing", "Quick to decide"], correctIndex: 1 },
  { id: 57, category: "verbal", text: "INEXORABLE most nearly means:", options: ["Easily persuaded", "Relentless and unstoppable", "Temporary and brief", "Kind and forgiving"], correctIndex: 1 },
  { id: 58, category: "verbal", text: "Doctor : Stethoscope :: Astronomer : ___", options: ["Satellite", "Telescope", "Microscope", "Compass"], correctIndex: 1 },
  { id: 59, category: "verbal", text: "SOLICITOUS behaviour is best described as:", options: ["Showing care and concern for another's wellbeing", "Aggressively pursuing personal gain", "Openly hostile and confrontational", "Completely indifferent to others"], correctIndex: 0 },
  { id: 60, category: "verbal", text: "The council's decision was ___; members could not agree on a single course of action.", options: ["Unanimous", "Decisive", "Divisive", "Conclusive"], correctIndex: 2 },
  { id: 61, category: "verbal", text: "MAGNILOQUENT most nearly means:", options: ["Pompous and using inflated language", "Quiet and reserved", "Honest and direct", "Kind and gentle"], correctIndex: 0 },
  { id: 62, category: "verbal", text: "IMMUTABLE most nearly means:", options: ["Easily changed", "Temporary", "Unchangeable and permanent", "Mysterious and unknown"], correctIndex: 2 },
  { id: 63, category: "verbal", text: "FORTUITOUS most nearly means:", options: ["Unfortunate and tragic", "Happening by lucky chance", "Planned and deliberate", "Extremely brave"], correctIndex: 1 },
  { id: 64, category: "verbal", text: "TRUCULENT most nearly means:", options: ["Peaceful and cooperative", "Eager to argue or fight", "Shy and withdrawn", "Honest and fair"], correctIndex: 1 },
  { id: 65, category: "verbal", text: "SUPERCILIOUS most nearly means:", options: ["Very humble and modest", "Behaving as if superior to others", "Overly generous", "Deeply religious"], correctIndex: 1 },
  { id: 66, category: "verbal", text: "INDOLENT most nearly means:", options: ["Hard-working and diligent", "Lazy and avoiding activity", "Clever and resourceful", "Rude and offensive"], correctIndex: 1 },
  { id: 67, category: "verbal", text: "Surgeon : Scalpel :: Carpenter : ___", options: ["Nail", "Saw", "Plank", "Blueprint"], correctIndex: 1 },
  { id: 68, category: "verbal", text: "GREGARIOUS most nearly means the OPPOSITE of:", options: ["Sociable", "Solitary", "Friendly", "Cheerful"], correctIndex: 1 },
  { id: 69, category: "verbal", text: "The professor's lecture was so ___ that many students fell asleep.", options: ["Stimulating", "Riveting", "Monotonous", "Provocative"], correctIndex: 2 },
  { id: 70, category: "verbal", text: "MALADROIT most nearly means:", options: ["Highly skilled", "Clumsy and awkward", "Deeply loyal", "Quietly confident"], correctIndex: 1 },
  { id: 71, category: "verbal", text: "ANOMALOUS most nearly means:", options: ["Normal and expected", "Deviating from what is standard", "Completely obvious", "Strictly regulated"], correctIndex: 1 },
  { id: 72, category: "verbal", text: "PERFIDIOUS most nearly means:", options: ["Loyal and trustworthy", "Deceitful and untrustworthy", "Calm and measured", "Brave and determined"], correctIndex: 1 },
  { id: 73, category: "verbal", text: "All mammals have lungs. Whales are mammals. Which conclusion MUST follow?", options: ["Whales breathe through gills", "Whales have lungs", "Some mammals do not have lungs", "Whales are not mammals"], correctIndex: 1 },
  { id: 74, category: "verbal", text: "SALIENT most nearly means:", options: ["Hidden and obscure", "Most noticeable or important", "Extremely dangerous", "Consistently unreliable"], correctIndex: 1 },
  { id: 75, category: "verbal", text: "ACUMEN most nearly means:", options: ["Lack of intelligence", "Keenness and ability to make good judgements", "A strong desire for revenge", "Physical strength"], correctIndex: 1 },
  { id: 76, category: "verbal", text: "PENURY most nearly means:", options: ["Great wealth", "Extreme poverty", "Complete isolation", "Physical pain"], correctIndex: 1 },
  { id: 77, category: "verbal", text: "The politician's promises were merely ___; she had no intention of keeping them.", options: ["Sincere", "Binding", "Rhetoric", "Contractual"], correctIndex: 2 },
  { id: 78, category: "verbal", text: "INTREPID most nearly means:", options: ["Easily frightened", "Fearless and adventurous", "Calm and unemotional", "Uncertain and hesitant"], correctIndex: 1 },
  { id: 79, category: "verbal", text: "DIFFIDENT most nearly means:", options: ["Confident and assertive", "Modest and shy", "Angry and irritable", "Persistent and stubborn"], correctIndex: 1 },
  { id: 80, category: "verbal", text: "PEDANTIC most nearly means:", options: ["Practical and flexible", "Overly concerned with minor details or rules", "Creative and imaginative", "Open-minded and liberal"], correctIndex: 1 },
  { id: 81, category: "verbal", text: "ZEALOT : CAUSE :: MERCENARY : ___", options: ["Country", "Ideal", "Money", "Principle"], correctIndex: 2 },
  { id: 82, category: "verbal", text: "Which of the following sentences contains a grammatical error?", options: ["The committee has reached its decision.", "Each of the students have submitted their work.", "Neither of the options was acceptable.", "The data are inconclusive."], correctIndex: 1 },
  { id: 83, category: "verbal", text: "COMPLACENT most nearly means:", options: ["Anxious and worried", "Self-satisfied, often ignoring danger", "Extremely generous", "Overly cautious"], correctIndex: 1 },
  { id: 84, category: "verbal", text: "ELUCIDATE most nearly means:", options: ["To confuse deliberately", "To make clear and explain", "To hide from view", "To destroy completely"], correctIndex: 1 },
  { id: 85, category: "verbal", text: "LABYRINTHINE most nearly means:", options: ["Simple and straightforward", "Complicated with many twists", "Bright and colourful", "Short and concise"], correctIndex: 1 },
  { id: 86, category: "verbal", text: "VERACIOUS most nearly means:", options: ["Untrustworthy", "Truthful", "Violent", "Vague"], correctIndex: 1 },
  { id: 87, category: "verbal", text: "OBDURATE most nearly means:", options: ["Open to persuasion", "Stubbornly refusing to change opinion", "Extremely generous", "Quickly frightened"], correctIndex: 1 },
  { id: 88, category: "verbal", text: "SYCOPHANT : FLATTERY :: DEMAGOGUE : ___", options: ["Silence", "Rhetoric", "Integrity", "Diplomacy"], correctIndex: 1 },
  { id: 89, category: "verbal", text: "INVETERATE most nearly means:", options: ["New and inexperienced", "Having a firmly established habit", "Occasionally practised", "Freshly motivated"], correctIndex: 1 },
  { id: 90, category: "verbal", text: "Which sentence uses the SUBJUNCTIVE mood correctly?", options: ["If he was here, he would help.", "If he were here, he would help.", "If he is here, he would help.", "If he will be here, he would help."], correctIndex: 1 },
  { id: 91, category: "verbal", text: "LETHARGIC most nearly means the OPPOSITE of:", options: ["Energetic", "Tired", "Slow", "Drowsy"], correctIndex: 0 },
  { id: 92, category: "verbal", text: "Some A are B. All B are C. Which conclusion is NECESSARILY true?", options: ["All A are C", "Some A are C", "All C are A", "No A are C"], correctIndex: 1 },
  { id: 93, category: "verbal", text: "PARAGON most nearly means:", options: ["A perfect example of something", "A common mistake", "A difficult challenge", "An unusual event"], correctIndex: 0 },
  { id: 94, category: "verbal", text: "CAUSTIC most nearly means:", options: ["Kind and encouraging", "Sarcastic and biting", "Dull and unremarkable", "Warm and affectionate"], correctIndex: 1 },
  { id: 95, category: "verbal", text: "PRECOCIOUS most nearly means:", options: ["Developing skills later than normal", "Having developed skills unusually early", "Slow to learn new things", "Resistant to change"], correctIndex: 1 },
  { id: 96, category: "verbal", text: "He was known for his ___: he never spent a single penny unnecessarily.", options: ["Extravagance", "Generosity", "Frugality", "Impulsiveness"], correctIndex: 2 },
  { id: 97, category: "verbal", text: "AMALGAMATE most nearly means:", options: ["To separate into pieces", "To combine or unite", "To analyse carefully", "To distribute widely"], correctIndex: 1 },
  { id: 98, category: "verbal", text: "TENDENTIOUS most nearly means:", options: ["Completely impartial", "Promoting a particular point of view", "Based on thorough research", "Open to many interpretations"], correctIndex: 1 },
  { id: 99, category: "verbal", text: "ALACRITY most nearly means:", options: ["Slowness and reluctance", "Cheerful willingness and speed", "Extreme caution", "Deep sadness"], correctIndex: 1 },
  { id: 100, category: "verbal", text: "EPHEMERAL : PERMANENT :: TACIT : ___", options: ["Silent", "Spoken aloud", "Understood", "Agreed"], correctIndex: 1 },
  { id: 201, category: "verbal", text: "SARDONIC most nearly means:", options: ["Warm and generous", "Grimly mocking or cynical", "Deeply sad", "Overly enthusiastic"], correctIndex: 1 },
  { id: 202, category: "verbal", text: "PROFLIGATE most nearly means:", options: ["Thrifty and careful", "Recklessly extravagant", "Modest and quiet", "Brave and bold"], correctIndex: 1 },
  { id: 203, category: "verbal", text: "INSIDIOUS most nearly means:", options: ["Completely open and honest", "Proceeding harmfully in a subtle way", "Bold and aggressive", "Cheerful and kind"], correctIndex: 1 },
  { id: 204, category: "verbal", text: "MUNIFICENT most nearly means:", options: ["Extremely generous", "Extremely angry", "Clever and deceptive", "Loud and demanding"], correctIndex: 0 },
  { id: 205, category: "verbal", text: "BELLICOSE most nearly means:", options: ["Peaceful and cooperative", "Eager for war or conflict", "Thoughtful and wise", "Shy and reserved"], correctIndex: 1 },
  { id: 206, category: "verbal", text: "TEMERITY most nearly means:", options: ["Excessive caution", "Reckless boldness", "Great wisdom", "Deep sadness"], correctIndex: 1 },
  { id: 207, category: "verbal", text: "PERFUNCTORY most nearly means:", options: ["Done with great care", "Carried out with minimal effort or interest", "Emotional and expressive", "Completely unpredictable"], correctIndex: 1 },
  { id: 208, category: "verbal", text: "SAGACIOUS most nearly means:", options: ["Foolish and naive", "Having good judgement and wisdom", "Extremely brave", "Easily frightened"], correctIndex: 1 },
  { id: 209, category: "verbal", text: "IGNOMINIOUS most nearly means:", options: ["Worthy of great honour", "Deserving or causing public disgrace", "Widely celebrated", "Extremely brave"], correctIndex: 1 },
  { id: 210, category: "verbal", text: "CALUMNY most nearly means:", options: ["A sincere compliment", "A false and damaging statement about someone", "A legal agreement", "An official ceremony"], correctIndex: 1 },
  { id: 211, category: "verbal", text: "IMPECUNIOUS most nearly means:", options: ["Extremely wealthy", "Having very little money", "Highly educated", "Physically strong"], correctIndex: 1 },
  { id: 212, category: "verbal", text: "RECONDITE most nearly means:", options: ["Well-known and popular", "Obscure and known only to specialists", "Simple and easy to understand", "Recent and new"], correctIndex: 1 },
  { id: 213, category: "verbal", text: "REPUDIATE most nearly means:", options: ["To confirm strongly", "To formally reject or refuse to accept", "To delay deliberately", "To praise lavishly"], correctIndex: 1 },
  { id: 214, category: "verbal", text: "MALLEABLE most nearly means:", options: ["Rigid and unchangeable", "Easily shaped or influenced", "Fragile and delicate", "Slow and methodical"], correctIndex: 1 },
  { id: 215, category: "verbal", text: "GAINSAY most nearly means:", options: ["To strongly agree with", "To speak against or contradict", "To praise highly", "To ignore completely"], correctIndex: 1 },
  { id: 216, category: "verbal", text: "CUPIDITY most nearly means:", options: ["Generosity and kindness", "Greed for money or possessions", "Love and affection", "Anger and resentment"], correctIndex: 1 },
  { id: 217, category: "verbal", text: "INIMITABLE most nearly means:", options: ["Easy to copy or reproduce", "Too distinctive to be imitated", "Widely disliked", "Quickly forgotten"], correctIndex: 1 },
  { id: 218, category: "verbal", text: "EXCORIATE most nearly means:", options: ["To praise enthusiastically", "To criticise or censure very severely", "To examine carefully", "To reward generously"], correctIndex: 1 },
  { id: 219, category: "verbal", text: "DILETTANTE : EXPERTISE :: NOVICE : ___", options: ["Skill", "Effort", "Interest", "Practice"], correctIndex: 0 },
  { id: 220, category: "verbal", text: "FURTIVE most nearly means the OPPOSITE of:", options: ["Secretive", "Open and unconcealed", "Hurried", "Cautious"], correctIndex: 1 },
  { id: 221, category: "verbal", text: "IMPUGN most nearly means:", options: ["To defend against criticism", "To call into question or attack as false", "To agree wholeheartedly", "To ignore deliberately"], correctIndex: 1 },
  { id: 222, category: "verbal", text: "The committee's DRACONIAN measures were criticised by rights groups. DRACONIAN means:", options: ["Lenient and forgiving", "Excessively harsh and severe", "Well-thought-out and balanced", "Widely popular and celebrated"], correctIndex: 1 },
  { id: 223, category: "verbal", text: "LASSITUDE most nearly means:", options: ["Great energy and enthusiasm", "Physical or mental weariness", "Boldness and courage", "Sharp intelligence"], correctIndex: 1 },
  { id: 224, category: "verbal", text: "EXIGENT most nearly means:", options: ["Relaxed and flexible", "Pressing and demanding immediate attention", "Generous and giving", "Clear and simple"], correctIndex: 1 },
  { id: 225, category: "verbal", text: "PELLUCID most nearly means:", options: ["Difficult to understand", "Transparently clear and easily understood", "Extremely dark", "Very old and worn"], correctIndex: 1 },
  { id: 226, category: "verbal", text: "A MOOT point is one that is:", options: ["Absolutely decided and settled", "Open to debate or no longer practically relevant", "Extremely important", "Widely misunderstood"], correctIndex: 1 },
  { id: 227, category: "verbal", text: "HARBINGER most nearly means:", options: ["A summary of events", "A person or thing that signals something approaching", "A formal apology", "A strict set of rules"], correctIndex: 1 },
  { id: 228, category: "verbal", text: "INDIGNANT most nearly means:", options: ["Pleased and satisfied", "Feeling righteous anger at unfairness", "Extremely tired", "Deeply ashamed"], correctIndex: 1 },
  { id: 229, category: "verbal", text: "TERSE most nearly means:", options: ["Lengthy and detailed", "Sparing with words; brief and abrupt", "Warmly friendly", "Highly technical"], correctIndex: 1 },
  { id: 230, category: "verbal", text: "HETEROGENEOUS most nearly means the OPPOSITE of:", options: ["Mixed and varied", "Uniform and of the same kind", "Foreign or alien", "Large and numerous"], correctIndex: 1 },
  { id: 231, category: "verbal", text: "CONSTERNATION most nearly means:", options: ["Great joy and celebration", "A feeling of anxiety or dismay", "Complete boredom", "Strong admiration"], correctIndex: 1 },
  { id: 232, category: "verbal", text: "TURPITUDE most nearly means:", options: ["Great virtue", "Wickedness and moral depravity", "Physical strength", "Natural talent"], correctIndex: 1 },
  { id: 233, category: "verbal", text: "The artist's work was so ___ that critics struggled to categorise it under any existing movement.", options: ["Conventional", "Derivative", "Idiosyncratic", "Predictable"], correctIndex: 2 },
  { id: 234, category: "verbal", text: "ACCOLADE most nearly means:", options: ["A form of punishment", "An award or expression of praise", "A sharp criticism", "A series of questions"], correctIndex: 1 },
  { id: 235, category: "verbal", text: "DOGMATIC most nearly means:", options: ["Open to different opinions", "Asserting opinions very forcefully as if beyond question", "Vague and uncertain", "Humble and modest"], correctIndex: 1 },
  { id: 236, category: "verbal", text: "PANACEA most nearly means:", options: ["A difficult problem", "A remedy claimed to cure all diseases or problems", "An important question", "A serious warning"], correctIndex: 1 },
  { id: 237, category: "verbal", text: "MENDACIOUS most nearly means:", options: ["Honest and straightforward", "Prone to lying and deceit", "Exceedingly kind", "Confused and unclear"], correctIndex: 1 },
  { id: 238, category: "verbal", text: "PROLIFIC most nearly means:", options: ["Producing very little", "Producing abundant work, results, or offspring", "Highly selective", "Inconsistent and unpredictable"], correctIndex: 1 },
  { id: 239, category: "verbal", text: "QUERULOUS most nearly means:", options: ["Content and satisfied", "Complaining in a petulant or whining way", "Inquisitive and curious", "Loud and aggressive"], correctIndex: 1 },
  { id: 240, category: "verbal", text: "DESULTORY most nearly means:", options: ["Carefully planned and systematic", "Going from one thing to another without purpose or plan", "Energetic and determined", "Slow and careful"], correctIndex: 1 },
  { id: 241, category: "verbal", text: "OSTRACISE most nearly means:", options: ["To welcome enthusiastically", "To exclude from a group or society", "To openly celebrate", "To carefully study"], correctIndex: 1 },
  { id: 242, category: "verbal", text: "VERBOSE most nearly means the OPPOSITE of:", options: ["Wordy", "Concise", "Detailed", "Expressive"], correctIndex: 1 },
  { id: 243, category: "verbal", text: "All cats have whiskers. Tom has whiskers. Which conclusion is VALID?", options: ["Tom is definitely a cat.", "Tom may be a cat, but this cannot be confirmed from these premises alone.", "Tom cannot be a cat.", "All animals with whiskers are cats."], correctIndex: 1 },
  { id: 244, category: "verbal", text: "No reptiles are warm-blooded. Iguanas are reptiles. Which conclusion MUST follow?", options: ["Some iguanas are warm-blooded.", "Iguanas are not warm-blooded.", "Some warm-blooded animals are iguanas.", "All iguanas have scales."], correctIndex: 1 },
  { id: 245, category: "verbal", text: "DISPARATE most nearly means:", options: ["Very similar in nature", "Essentially different in kind or quality", "Completely equal", "Easily compared"], correctIndex: 1 },
  { id: 246, category: "verbal", text: "PENULTIMATE most nearly means:", options: ["The very last", "Second from the last", "The very first", "Second from the first"], correctIndex: 1 },
  { id: 247, category: "verbal", text: "HUBRIS most nearly means:", options: ["Great humility", "Excessive pride or arrogance, often leading to downfall", "Quiet wisdom", "Deep sadness"], correctIndex: 1 },
  { id: 248, category: "verbal", text: "CONTRITE most nearly means:", options: ["Feeling no remorse", "Feeling deeply sorry and remorseful for wrongdoing", "Highly satisfied", "Quietly confident"], correctIndex: 1 },
  { id: 249, category: "verbal", text: "ENMITY most nearly means:", options: ["Deep friendship", "Active hostility or ill feeling between people", "Mutual respect", "Polite indifference"], correctIndex: 1 },
  { id: 250, category: "verbal", text: "EXTRAPOLATE most nearly means:", options: ["To summarise existing data", "To extend known information to predict or infer beyond it", "To deliberately falsify results", "To express a strong opinion"], correctIndex: 1 },
  { id: 251, category: "verbal", text: "TANGENTIAL most nearly means:", options: ["Directly and closely relevant", "Only slightly connected to the main subject", "Extremely important", "Completely unrelated in every way"], correctIndex: 1 },
  { id: 252, category: "verbal", text: "AVARICE most nearly means:", options: ["Extreme generosity", "Extreme greed for wealth or gain", "Deep religious faith", "A strong sense of justice"], correctIndex: 1 },
  { id: 253, category: "verbal", text: "EPHEMERAL : LASTING :: OPAQUE : ___", options: ["Dark", "Cloudy", "Transparent", "Solid"], correctIndex: 2 },
  { id: 254, category: "verbal", text: "DISSEMBLE most nearly means:", options: ["To construct carefully", "To conceal one's true motives or feelings", "To analyse in detail", "To distribute widely"], correctIndex: 1 },
  { id: 255, category: "verbal", text: "QUERULOUS : CONTENTMENT :: AVARICIOUS : ___", options: ["Wealth", "Greed", "Generosity", "Ambition"], correctIndex: 2 },
  { id: 256, category: "verbal", text: "ANOMALY most nearly means:", options: ["Something entirely expected", "Something that deviates from what is standard or normal", "A strict rule", "A clear pattern"], correctIndex: 1 },
  { id: 257, category: "verbal", text: "MISANTHROPE most nearly means:", options: ["A person who loves everyone", "A person who dislikes or distrusts humanity", "A person who loves animals", "A person who avoids conflict"], correctIndex: 1 },
  { id: 258, category: "verbal", text: "IMMINENT most nearly means:", options: ["Unlikely to happen", "About to happen very soon", "Already happened", "Happening far in the future"], correctIndex: 1 },
  { id: 259, category: "verbal", text: "A PARADOX is:", options: ["A statement that is clearly false", "A seemingly contradictory statement that may nonetheless be true", "A simple comparison using 'like' or 'as'", "A strong exaggeration for effect"], correctIndex: 1 },
  { id: 260, category: "verbal", text: "PROSCRIBE most nearly means:", options: ["To recommend officially", "To officially forbid or prohibit", "To describe in detail", "To plan carefully"], correctIndex: 1 },
  { id: 261, category: "verbal", text: "APLOMB most nearly means:", options: ["Great anxiety under pressure", "Self-confidence and composure, especially in difficulty", "Anger at injustice", "Physical agility"], correctIndex: 1 },
  { id: 262, category: "verbal", text: "CULPABLE most nearly means:", options: ["Completely innocent", "Deserving blame or censure", "Highly praised", "Easily forgiven"], correctIndex: 1 },
  { id: 263, category: "verbal", text: "EXONERATE most nearly means:", options: ["To find formally guilty", "To officially absolve from blame or criminal charges", "To delay judgement", "To punish severely"], correctIndex: 1 },
  { id: 264, category: "verbal", text: "PLETHORA most nearly means:", options: ["A severe shortage", "An excessive or overabundant amount", "A balanced amount", "A total absence"], correctIndex: 1 },
  { id: 265, category: "verbal", text: "FORTITUDE most nearly means:", options: ["Physical strength", "Courage and resilience in the face of adversity", "Extreme caution", "Intellectual brilliance"], correctIndex: 1 },
  { id: 266, category: "verbal", text: "AMBIVALENT : CONVICTION :: TACITURN : ___", options: ["Silence", "Eloquence", "Doubt", "Reserve"], correctIndex: 1 },
  { id: 267, category: "verbal", text: "IMPECUNIOUS : WEALTHY :: INTREPID : ___", options: ["Brave", "Fearful", "Cautious", "Adventurous"], correctIndex: 1 },
  { id: 268, category: "verbal", text: "A PYRRHIC victory is one that:", options: ["Is achieved with no losses", "Comes at too great a cost to the victor", "Is won easily and quickly", "Benefits all parties involved"], correctIndex: 1 },
  { id: 269, category: "verbal", text: "INGENUOUS most nearly means:", options: ["Clever and deceptive", "Innocent, trusting, and unsuspecting", "Bold and daring", "Cold and calculating"], correctIndex: 1 },
  { id: 270, category: "verbal", text: "PIQUE most nearly means:", options: ["A feeling of great joy", "A feeling of irritation at being disrespected or slighted", "A feeling of deep shame", "A feeling of great pride"], correctIndex: 1 },
  { id: 271, category: "verbal", text: "CATALYST most nearly means:", options: ["Something that prevents change", "Something that causes or greatly accelerates change", "Something that documents change", "Something that reverses change"], correctIndex: 1 },
  { id: 272, category: "verbal", text: "EGREGIOUS most nearly means:", options: ["Slightly below average", "Outstandingly bad or shocking", "Quietly impressive", "Widely admired"], correctIndex: 1 },
  { id: 273, category: "verbal", text: "NADIR most nearly means:", options: ["The highest point", "The lowest point of something", "The midpoint", "The starting point"], correctIndex: 1 },
  { id: 274, category: "verbal", text: "CONVOLUTED most nearly means:", options: ["Clear and direct", "Extremely complex and difficult to follow", "Short and simple", "Well-organised and logical"], correctIndex: 1 },
  { id: 275, category: "verbal", text: "LACKLUSTER most nearly means:", options: ["Brilliant and shining", "Lacking vitality, force, or conviction", "Detailed and thorough", "Strict and demanding"], correctIndex: 1 },
  { id: 276, category: "verbal", text: "Which sentence is CORRECT?", options: ["Whom did you speak with?", "Who did you spoke with?", "Whom did you spoke with?", "Who did you speak to that person?"], correctIndex: 0 },
  { id: 277, category: "verbal", text: "VERBOSE : TERSE :: MUNIFICENT : ___", options: ["Generous", "Wealthy", "Miserly", "Humble"], correctIndex: 2 },
  { id: 278, category: "verbal", text: "Which of the following is the BEST example of an ad hominem fallacy?", options: ["Your theory is wrong because your data is incomplete.", "His proposal should be rejected because he was once convicted of fraud.", "Most scientists agree with this conclusion.", "This policy has worked in three other countries."], correctIndex: 1 },
  { id: 279, category: "verbal", text: "PIOUS most nearly means:", options: ["Deeply devout and religiously reverent", "Loud and boastful", "Quietly thoughtful", "Strict and severe"], correctIndex: 0 },
  { id: 280, category: "verbal", text: "Identify the sentence with a MISPLACED modifier:", options: ["She quickly ran to the store.", "He handed out the flyers wearing a hat.", "The dog barked loudly at the stranger.", "They carefully read the report."], correctIndex: 1 },
  { id: 281, category: "verbal", text: "TERSE most nearly means the OPPOSITE of:", options: ["Brief", "Lengthy and verbose", "Clear", "Technical"], correctIndex: 1 },
  { id: 282, category: "verbal", text: "She was ___ about the new policy — neither fully supporting it nor opposing it.", options: ["Fervent", "Ambivalent", "Adamant", "Enthusiastic"], correctIndex: 1 },
  { id: 283, category: "verbal", text: "Which word is INCORRECTLY used? 'The affect of the new policy was immediately visible.'", options: ["policy", "visible", "affect", "immediately"], correctIndex: 2 },
  { id: 284, category: "verbal", text: "PLAUSIBLE most nearly means:", options: ["Clearly false", "Seeming reasonable or probable", "Definitely and conclusively proven", "Widely disliked"], correctIndex: 1 },
  { id: 285, category: "verbal", text: "The researcher's conclusion was ___, supported by overwhelming evidence from multiple independent studies.", options: ["Tenuous", "Speculative", "Irrefutable", "Preliminary"], correctIndex: 2 },
  { id: 286, category: "verbal", text: "HARBINGER : ARRIVAL :: SYMPTOM : ___", options: ["Medicine", "Disease", "Doctor", "Recovery"], correctIndex: 1 },
  { id: 287, category: "verbal", text: "DEFERENTIAL most nearly means:", options: ["Bold and assertive", "Showing respectful submission or yielding to another's judgement", "Critical and challenging", "Completely neutral"], correctIndex: 1 },
  { id: 288, category: "verbal", text: "Which sentence is GRAMMATICALLY CORRECT?", options: ["Between you and I, this is wrong.", "Between you and me, this is wrong.", "Between you and myself, this is wrong.", "Between I and you, this is wrong."], correctIndex: 1 },
  { id: 289, category: "verbal", text: "LOQUACIOUS : SILENCE :: BELLICOSE : ___", options: ["Conflict", "Victory", "Peace", "Strength"], correctIndex: 2 },
  { id: 290, category: "verbal", text: "PREAMBLE most nearly means:", options: ["A brief preliminary introduction to a speech or document", "A conclusion or summary", "A main argument", "A detailed proof"], correctIndex: 0 },
  { id: 291, category: "verbal", text: "INTRACTABLE most nearly means:", options: ["Easily managed", "Hard to control or deal with", "Quickly resolved", "Openly defiant"], correctIndex: 1 },
  { id: 292, category: "verbal", text: "The CEO was ___ about the new proposal, taking no time to consider its merits before rejecting it.", options: ["Deliberate", "Peremptory", "Thoughtful", "Analytical"], correctIndex: 1 },
  { id: 293, category: "verbal", text: "CREDULOUS most nearly means:", options: ["Difficult to convince", "Too willing to believe things without proper evidence", "Highly intelligent", "Deeply sceptical"], correctIndex: 1 },
  { id: 294, category: "verbal", text: "MAGNANIMOUS : PETTINESS :: PRUDENT : ___", options: ["Wisdom", "Caution", "Recklessness", "Patience"], correctIndex: 2 },
  { id: 295, category: "verbal", text: "OSTENSIBLE most nearly means:", options: ["Hidden and concealed", "Appearing as such, but not necessarily so", "Completely obvious to all", "Firmly established"], correctIndex: 1 },
  { id: 296, category: "verbal", text: "His speech was full of ___, with endless circular arguments that never reached a conclusion.", options: ["Brevity", "Concision", "Verbosity", "Precision"], correctIndex: 2 },
  { id: 297, category: "verbal", text: "CONTIGUOUS most nearly means:", options: ["Far apart", "Sharing a common boundary; touching", "Completely different", "Temporary and brief"], correctIndex: 1 },
  { id: 298, category: "verbal", text: "SUPERFLUOUS most nearly means:", options: ["Essential and necessary", "More than what is needed or wanted", "Extremely important", "Carefully selected"], correctIndex: 1 },
  { id: 299, category: "verbal", text: "ACRIMONY : BITTERNESS :: LEVITY : ___", options: ["Sadness", "Humour and light-heartedness", "Seriousness", "Gravity"], correctIndex: 1 },
];

// ── 100 Quantitative Questions (IDs 101-200) ─────────────────────────────────

export const QUANT_QUESTIONS: ScholarQuestion[] = [
  { id: 101, category: "quant", text: "A train travels 300 km in 2.5 hours. What is its average speed?", options: ["100 km/h", "110 km/h", "120 km/h", "130 km/h"], correctIndex: 2 },
  { id: 102, category: "quant", text: "A shirt costs $45 after a 25% discount. What was its original price?", options: ["$55", "$60", "$65", "$70"], correctIndex: 1 },
  { id: 103, category: "quant", text: "Find the next term in the series: 2, 6, 18, 54, ___", options: ["108", "144", "162", "216"], correctIndex: 2 },
  { id: 104, category: "quant", text: "If 3x + 7 = 22, what is x?", options: ["3", "4", "5", "6"], correctIndex: 2 },
  { id: 105, category: "quant", text: "A rectangle has a perimeter of 46 cm. If its length is 14 cm, what is its width?", options: ["7 cm", "8 cm", "9 cm", "10 cm"], correctIndex: 2 },
  { id: 106, category: "quant", text: "What percentage is 45 of 180?", options: ["20%", "25%", "30%", "35%"], correctIndex: 1 },
  { id: 107, category: "quant", text: "A car depreciates from $20,000 to $14,000 in one year. What is the depreciation percentage?", options: ["25%", "28%", "30%", "32%"], correctIndex: 2 },
  { id: 108, category: "quant", text: "The ratio of boys to girls is 3:5. If there are 120 students total, how many are girls?", options: ["45", "60", "75", "90"], correctIndex: 2 },
  { id: 109, category: "quant", text: "What is the compound interest on $5,000 at 10% per annum for 2 years?", options: ["$950", "$1,000", "$1,050", "$1,100"], correctIndex: 2 },
  { id: 110, category: "quant", text: "The average of 5 numbers is 18. If one is removed, the average becomes 16. What was the removed number?", options: ["22", "24", "26", "28"], correctIndex: 2 },
  { id: 111, category: "quant", text: "In how many ways can 4 different people be arranged in a straight line?", options: ["12", "16", "24", "32"], correctIndex: 2 },
  { id: 112, category: "quant", text: "Pipe A fills a tank in 6 hours; Pipe B in 4 hours. How long do they take together?", options: ["2.0 hours", "2.4 hours", "2.8 hours", "3.0 hours"], correctIndex: 1 },
  { id: 113, category: "quant", text: "A merchant buys goods for $240 and sells them for $300. What is the profit percentage?", options: ["20%", "22.5%", "25%", "28%"], correctIndex: 2 },
  { id: 114, category: "quant", text: "What is √(144 + 25)?", options: ["11", "12", "13", "14"], correctIndex: 2 },
  { id: 115, category: "quant", text: "Solve: 2x² − 8 = 0. What are the values of x?", options: ["x = ±1", "x = ±2", "x = ±4", "x = 4 only"], correctIndex: 1 },
  { id: 116, category: "quant", text: "A worker earns $1,200/month and saves 15%. How much does she save in 8 months?", options: ["$1,260", "$1,320", "$1,380", "$1,440"], correctIndex: 3 },
  { id: 117, category: "quant", text: "A ladder 13 m long leans against a wall. If its foot is 5 m from the wall, how high does it reach?", options: ["10 m", "11 m", "12 m", "13 m"], correctIndex: 2 },
  { id: 118, category: "quant", text: "Simple interest on $2,400 at 5% per annum for 3 years is:", options: ["$240", "$300", "$360", "$420"], correctIndex: 2 },
  { id: 119, category: "quant", text: "The next number in the pattern 1, 4, 9, 16, 25, ___ is:", options: ["30", "36", "49", "64"], correctIndex: 1 },
  { id: 120, category: "quant", text: "If 20% of a number is 50, what is 35% of the same number?", options: ["75.5", "85.0", "87.5", "90.0"], correctIndex: 2 },
  { id: 121, category: "quant", text: "Two numbers are in the ratio 4:7. Their sum is 99. Find the larger number.", options: ["36", "54", "63", "72"], correctIndex: 2 },
  { id: 122, category: "quant", text: "A bus covers 240 km at 60 km/h and returns at 80 km/h. What is the average speed for the whole journey?", options: ["68.6 km/h", "69.5 km/h", "70.0 km/h", "72.0 km/h"], correctIndex: 0 },
  { id: 123, category: "quant", text: "How many prime numbers are there between 20 and 40?", options: ["3", "4", "5", "6"], correctIndex: 1 },
  { id: 124, category: "quant", text: "A square has a diagonal of 10√2 cm. What is its area?", options: ["50 cm²", "100 cm²", "150 cm²", "200 cm²"], correctIndex: 1 },
  { id: 125, category: "quant", text: "Evaluate: 3³ + 4² − 2⁵", options: ["11", "13", "15", "17"], correctIndex: 0 },
  { id: 126, category: "quant", text: "A bag has 4 red and 6 blue balls. What is the probability of picking 2 red balls without replacement?", options: ["2/15", "4/25", "3/20", "1/6"], correctIndex: 0 },
  { id: 127, category: "quant", text: "A circular ring has outer radius 10 cm and inner radius 7 cm. What is its area? (π ≈ 3.14)", options: ["155.84 cm²", "158.12 cm²", "160.14 cm²", "162.40 cm²"], correctIndex: 2 },
  { id: 128, category: "quant", text: "A number when doubled and added to 36 gives 100. What is the number?", options: ["28", "30", "32", "34"], correctIndex: 2 },
  { id: 129, category: "quant", text: "If log₂(32) = x, what is x?", options: ["4", "5", "6", "8"], correctIndex: 1 },
  { id: 130, category: "quant", text: "A triangle has sides 7 cm, 24 cm, and 25 cm. What is its area?", options: ["64 cm²", "80 cm²", "84 cm²", "96 cm²"], correctIndex: 2 },
  { id: 131, category: "quant", text: "If x/3 = 9, what is 2x?", options: ["42", "48", "54", "60"], correctIndex: 2 },
  { id: 132, category: "quant", text: "A train 200 m long passes a pole in 10 seconds. What is its speed in km/h?", options: ["54 km/h", "60 km/h", "72 km/h", "80 km/h"], correctIndex: 2 },
  { id: 133, category: "quant", text: "Simplify: (2³ × 2⁴) ÷ 2⁵", options: ["2", "4", "8", "16"], correctIndex: 1 },
  { id: 134, category: "quant", text: "A shopkeeper marks an item at $150 and offers a 20% discount. What is the selling price?", options: ["$110", "$115", "$120", "$125"], correctIndex: 2 },
  { id: 135, category: "quant", text: "The sum of interior angles in a quadrilateral is:", options: ["180°", "270°", "360°", "540°"], correctIndex: 2 },
  { id: 136, category: "quant", text: "Find x: 5(x + 3) = 40", options: ["3", "4", "5", "6"], correctIndex: 2 },
  { id: 137, category: "quant", text: "A 30% salt solution contains 60 g of salt. What is the total weight of the solution?", options: ["150 g", "180 g", "200 g", "220 g"], correctIndex: 2 },
  { id: 138, category: "quant", text: "What is the LCM of 12 and 18?", options: ["24", "30", "36", "48"], correctIndex: 2 },
  { id: 139, category: "quant", text: "A man walks 3 km north and 4 km east. How far is he from his starting point?", options: ["4 km", "5 km", "6 km", "7 km"], correctIndex: 1 },
  { id: 140, category: "quant", text: "If a : b = 2 : 3 and b : c = 4 : 5, what is a : c?", options: ["8:15", "2:5", "4:9", "6:10"], correctIndex: 0 },
  { id: 141, category: "quant", text: "A sum doubles in 8 years at simple interest. What is the annual interest rate?", options: ["10%", "12%", "12.5%", "15%"], correctIndex: 2 },
  { id: 142, category: "quant", text: "What is the median of: 3, 7, 2, 9, 5, 1, 8?", options: ["3", "5", "7", "8"], correctIndex: 1 },
  { id: 143, category: "quant", text: "A cone has base radius 6 cm and height 8 cm. What is its slant height?", options: ["8 cm", "9 cm", "10 cm", "12 cm"], correctIndex: 2 },
  { id: 144, category: "quant", text: "Factorise: x² − 5x + 6", options: ["(x+2)(x+3)", "(x−2)(x−3)", "(x−1)(x−6)", "(x+1)(x−6)"], correctIndex: 1 },
  { id: 145, category: "quant", text: "In a class of 40 students, 60% are girls. How many boys are there?", options: ["12", "14", "16", "18"], correctIndex: 2 },
  { id: 146, category: "quant", text: "A sector has radius 7 cm and angle 90°. What is its area? (π ≈ 22/7)", options: ["35.5 cm²", "38.5 cm²", "42.0 cm²", "44.0 cm²"], correctIndex: 1 },
  { id: 147, category: "quant", text: "What is 15% of 240?", options: ["30", "32", "36", "40"], correctIndex: 2 },
  { id: 148, category: "quant", text: "Simplify: (3a²b)(4ab³)", options: ["7a²b³", "12a³b⁴", "12a²b⁴", "7a³b³"], correctIndex: 1 },
  { id: 149, category: "quant", text: "A tank is 40% full. After adding 60 litres it becomes 70% full. What is the total capacity?", options: ["150 litres", "180 litres", "200 litres", "240 litres"], correctIndex: 2 },
  { id: 150, category: "quant", text: "What is the sum of the interior angles of a hexagon?", options: ["540°", "620°", "720°", "840°"], correctIndex: 2 },
  { id: 151, category: "quant", text: "If f(x) = 2x² − 3, what is f(4)?", options: ["25", "27", "29", "31"], correctIndex: 2 },
  { id: 152, category: "quant", text: "Three children share $240 in ratio 1:2:3. What is the largest share?", options: ["$80", "$100", "$120", "$140"], correctIndex: 2 },
  { id: 153, category: "quant", text: "A rectangle has area 84 cm² and width 7 cm. What is its perimeter?", options: ["34 cm", "36 cm", "38 cm", "40 cm"], correctIndex: 2 },
  { id: 154, category: "quant", text: "What is the HCF of 24 and 36?", options: ["6", "8", "12", "18"], correctIndex: 2 },
  { id: 155, category: "quant", text: "Evaluate: 2⁰ + 3¹ + 4²", options: ["18", "19", "20", "21"], correctIndex: 2 },
  { id: 156, category: "quant", text: "A car travels at 90 km/h. How far does it travel in 40 minutes?", options: ["50 km", "55 km", "60 km", "65 km"], correctIndex: 2 },
  { id: 157, category: "quant", text: "Solve the inequality: 3x − 4 > 11", options: ["x > 3", "x > 4", "x > 5", "x > 6"], correctIndex: 2 },
  { id: 158, category: "quant", text: "A die is rolled once. What is the probability of getting a number greater than 4?", options: ["1/6", "1/4", "1/3", "1/2"], correctIndex: 2 },
  { id: 159, category: "quant", text: "The mode of: 4, 7, 2, 7, 3, 9, 7, 1 is:", options: ["2", "4", "7", "9"], correctIndex: 2 },
  { id: 160, category: "quant", text: "What is 3/4 + 5/6?", options: ["8/10", "19/12", "9/10", "7/6"], correctIndex: 1 },
  { id: 161, category: "quant", text: "A sphere has radius 3 cm. What is its volume? (π ≈ 3.14)", options: ["100.48 cm³", "108.00 cm³", "113.04 cm³", "120.00 cm³"], correctIndex: 2 },
  { id: 162, category: "quant", text: "Solve: |2x − 6| = 10", options: ["x = 8 only", "x = −2 only", "x = 8 or x = −2", "x = 4 or x = −1"], correctIndex: 2 },
  { id: 163, category: "quant", text: "The 7th term of an arithmetic sequence with first term 3 and common difference 4 is:", options: ["23", "25", "27", "29"], correctIndex: 2 },
  { id: 164, category: "quant", text: "How many diagonals does a pentagon have?", options: ["4", "5", "6", "8"], correctIndex: 1 },
  { id: 165, category: "quant", text: "A shopkeeper buys 100 items for $500 and sells them for $650. What is the profit per item?", options: ["$1.00", "$1.25", "$1.50", "$2.00"], correctIndex: 2 },
  { id: 166, category: "quant", text: "What is the reciprocal of 2/7?", options: ["2/7", "7/2", "14", "1/14"], correctIndex: 1 },
  { id: 167, category: "quant", text: "In a right triangle with opposite = 3 and adjacent = 4, what is sin θ?", options: ["3/4", "4/5", "3/5", "4/3"], correctIndex: 2 },
  { id: 168, category: "quant", text: "A geometric sequence has first term 5 and common ratio 3. What is the 4th term?", options: ["45", "90", "135", "180"], correctIndex: 2 },
  { id: 169, category: "quant", text: "40% of workers are female. If there are 90 males, how many workers in total?", options: ["120", "135", "150", "160"], correctIndex: 2 },
  { id: 170, category: "quant", text: "Simplify: √72", options: ["4√3", "6√2", "8√2", "9√2"], correctIndex: 1 },
  { id: 171, category: "quant", text: "What is 2.5 × 10³ + 3.5 × 10²?", options: ["2350", "2650", "2850", "3000"], correctIndex: 2 },
  { id: 172, category: "quant", text: "In a right-angled triangle, the two shorter sides are 9 cm and 12 cm. What is the hypotenuse?", options: ["13 cm", "14 cm", "15 cm", "16 cm"], correctIndex: 2 },
  { id: 173, category: "quant", text: "What is 25% of 25% of 400?", options: ["20", "25", "30", "35"], correctIndex: 1 },
  { id: 174, category: "quant", text: "A polygon has interior angles summing to 1,260°. How many sides does it have?", options: ["7", "8", "9", "10"], correctIndex: 2 },
  { id: 175, category: "quant", text: "Find the gradient of the line passing through (2, 3) and (6, 11):", options: ["1", "1.5", "2", "2.5"], correctIndex: 2 },
  { id: 176, category: "quant", text: "A cylinder has radius 5 cm and height 10 cm. What is its volume? (π ≈ 3.14)", options: ["628 cm³", "706 cm³", "785 cm³", "942 cm³"], correctIndex: 2 },
  { id: 177, category: "quant", text: "How many ways can a president and vice-president be chosen from 10 candidates?", options: ["45", "80", "90", "100"], correctIndex: 2 },
  { id: 178, category: "quant", text: "What is 30% of $1,250?", options: ["$350", "$365", "$375", "$400"], correctIndex: 2 },
  { id: 179, category: "quant", text: "Solve for y: 4y + 9 = 3y + 17", options: ["6", "7", "8", "9"], correctIndex: 2 },
  { id: 180, category: "quant", text: "A bag contains 3 white, 4 black, and 5 red marbles. What is the probability of picking a black marble?", options: ["1/4", "1/3", "5/12", "1/2"], correctIndex: 1 },
  { id: 181, category: "quant", text: "Evaluate: (−3)² + (−2)³", options: ["−1", "1", "3", "17"], correctIndex: 1 },
  { id: 182, category: "quant", text: "Two angles of a triangle are 40° and 75°. What is the third angle?", options: ["55°", "60°", "65°", "70°"], correctIndex: 2 },
  { id: 183, category: "quant", text: "A man invests $2,000 at 4% simple interest per year. How much interest does he earn in 5 years?", options: ["$300", "$350", "$400", "$450"], correctIndex: 2 },
  { id: 184, category: "quant", text: "What is the next prime number after 23?", options: ["25", "27", "29", "31"], correctIndex: 2 },
  { id: 185, category: "quant", text: "Simplify: (x² − 9) ÷ (x − 3)", options: ["x − 3", "x + 3", "x² − 3", "x + 9"], correctIndex: 1 },
  { id: 186, category: "quant", text: "The circumference of a circle is 44 cm. What is its radius? (π ≈ 22/7)", options: ["5 cm", "6 cm", "7 cm", "8 cm"], correctIndex: 2 },
  { id: 187, category: "quant", text: "Evaluate: log₁₀(1000)", options: ["2", "3", "4", "10"], correctIndex: 1 },
  { id: 188, category: "quant", text: "A train moving at 60 km/h takes 2 hours to travel between two cities. How far apart are they?", options: ["90 km", "100 km", "120 km", "140 km"], correctIndex: 2 },
  { id: 189, category: "quant", text: "P(A) = 0.4 and P(B) = 0.3 and they are independent. What is P(A and B)?", options: ["0.07", "0.10", "0.12", "0.70"], correctIndex: 2 },
  { id: 190, category: "quant", text: "The product of two consecutive even numbers is 168. What are the numbers?", options: ["10 and 12", "12 and 14", "14 and 16", "8 and 10"], correctIndex: 1 },
  { id: 191, category: "quant", text: "Expand: (2x + 3)²", options: ["4x² + 6x + 9", "4x² + 12x + 9", "2x² + 12x + 9", "4x² + 9"], correctIndex: 1 },
  { id: 192, category: "quant", text: "How many significant figures are in 0.00506?", options: ["2", "3", "4", "5"], correctIndex: 1 },
  { id: 193, category: "quant", text: "A school has 600 students. 40% study science and 35% study arts. How many study neither?", options: ["100", "120", "150", "180"], correctIndex: 2 },
  { id: 194, category: "quant", text: "If the point (k, 4) lies on the line y = 2x − 2, find k:", options: ["2", "3", "4", "5"], correctIndex: 1 },
  { id: 195, category: "quant", text: "A sales tax of 7.5% is added to an $80 item. What is the total cost?", options: ["$84.00", "$85.50", "$86.00", "$87.50"], correctIndex: 2 },
  { id: 196, category: "quant", text: "What is the range of: 12, 7, 19, 3, 15, 8?", options: ["12", "14", "16", "19"], correctIndex: 2 },
  { id: 197, category: "quant", text: "Simplify: 5! ÷ 3!", options: ["15", "20", "60", "120"], correctIndex: 1 },
  { id: 198, category: "quant", text: "If sin 30° = 0.5, what is cos 60°?", options: ["0.25", "0.5", "0.75", "1.0"], correctIndex: 1 },
  { id: 199, category: "quant", text: "A 60 m rope is cut in ratio 2:3. What is the length of the longer piece?", options: ["24 m", "30 m", "36 m", "40 m"], correctIndex: 2 },
  { id: 200, category: "quant", text: "A town's population grew from 25,000 to 30,000 in one year. What is the percentage increase?", options: ["15%", "18%", "20%", "25%"], correctIndex: 2 },
  { id: 301, category: "quant", text: "What is the value of (−2)⁴?", options: ["−16", "8", "16", "−8"], correctIndex: 2 },
  { id: 302, category: "quant", text: "Simplify: (a + b)² − (a − b)²", options: ["2ab", "4ab", "a² + b²", "2(a² + b²)"], correctIndex: 1 },
  { id: 303, category: "quant", text: "Find the value of x: 2x/3 = 8", options: ["8", "10", "12", "16"], correctIndex: 2 },
  { id: 304, category: "quant", text: "A boat covers 36 km upstream in 4 hours and 36 km downstream in 3 hours. What is the speed of the current?", options: ["1.0 km/h", "1.5 km/h", "2.0 km/h", "3.0 km/h"], correctIndex: 1 },
  { id: 305, category: "quant", text: "Express 0.35 as a fraction in its simplest form:", options: ["35/100", "7/20", "3/5", "7/10"], correctIndex: 1 },
  { id: 306, category: "quant", text: "If the area of a square is 225 cm², what is its perimeter?", options: ["45 cm", "50 cm", "55 cm", "60 cm"], correctIndex: 3 },
  { id: 307, category: "quant", text: "The marks of 5 students are 72, 85, 90, 68, 75. What is their mean mark?", options: ["76", "77", "78", "79"], correctIndex: 2 },
  { id: 308, category: "quant", text: "In a survey, 60% liked apples and 40% liked oranges. If 20% liked both, what percentage liked neither?", options: ["10%", "15%", "20%", "25%"], correctIndex: 2 },
  { id: 309, category: "quant", text: "Find the roots of x² − 7x + 12 = 0:", options: ["x = 2 or x = 6", "x = 3 or x = 4", "x = 1 or x = 12", "x = 3 or x = −4"], correctIndex: 1 },
  { id: 310, category: "quant", text: "What is 1/3 of 3/4?", options: ["1/6", "1/4", "3/7", "4/7"], correctIndex: 1 },
  { id: 311, category: "quant", text: "A shopkeeper sells an item for $96, making a 20% profit. What was the cost price?", options: ["$70", "$75", "$80", "$85"], correctIndex: 2 },
  { id: 312, category: "quant", text: "How many terms are in the AP: 5, 8, 11, …, 50?", options: ["14", "15", "16", "17"], correctIndex: 2 },
  { id: 313, category: "quant", text: "Evaluate: 4! ÷ (2! × 2!)", options: ["3", "6", "8", "12"], correctIndex: 1 },
  { id: 314, category: "quant", text: "Three men can complete a job in 4 days. How long will 6 men take at the same rate?", options: ["1 day", "2 days", "3 days", "4 days"], correctIndex: 1 },
  { id: 315, category: "quant", text: "If log₅(x) = 3, what is x?", options: ["15", "25", "125", "625"], correctIndex: 2 },
  { id: 316, category: "quant", text: "A triangle has vertices A(0,0), B(4,0), C(0,3). What is its area?", options: ["5", "6", "7", "12"], correctIndex: 1 },
  { id: 317, category: "quant", text: "What is the sum of the first 10 terms of the AP: 2, 5, 8, …?", options: ["140", "145", "150", "155"], correctIndex: 3 },
  { id: 318, category: "quant", text: "Expand: (2x + 3)(x − 4)", options: ["2x² + 5x − 12", "2x² − 5x − 12", "2x² − 5x + 12", "2x² + 5x + 12"], correctIndex: 1 },
  { id: 319, category: "quant", text: "Find x: 4^x = 64", options: ["2", "3", "4", "8"], correctIndex: 1 },
  { id: 320, category: "quant", text: "A shopkeeper marks a price 40% above cost then gives a 10% discount. What is his actual profit %?", options: ["22%", "24%", "26%", "30%"], correctIndex: 2 },
  { id: 321, category: "quant", text: "If 5 is added to both numerator and denominator of 3/7, what is the new fraction in lowest terms?", options: ["8/10", "2/3", "5/9", "1/2"], correctIndex: 1 },
  { id: 322, category: "quant", text: "What is the smallest positive integer n such that 48n is a perfect square?", options: ["2", "3", "4", "6"], correctIndex: 1 },
  { id: 323, category: "quant", text: "A bus has 40 seats. If 75% are occupied, how many seats are empty?", options: ["8", "10", "12", "15"], correctIndex: 1 },
  { id: 324, category: "quant", text: "Three consecutive integers have a sum of 81. What is the middle integer?", options: ["25", "26", "27", "28"], correctIndex: 2 },
  { id: 325, category: "quant", text: "What is cos 0°?", options: ["0", "0.5", "1", "√2/2"], correctIndex: 2 },
  { id: 326, category: "quant", text: "If the volume of a cube is 64 cm³, what is the length of one side?", options: ["2 cm", "3 cm", "4 cm", "8 cm"], correctIndex: 2 },
  { id: 327, category: "quant", text: "A car's fuel efficiency is 12 km per litre. How many litres are needed for a 180 km trip?", options: ["12 L", "14 L", "15 L", "18 L"], correctIndex: 2 },
  { id: 328, category: "quant", text: "What is the value of ⁸C₂?", options: ["16", "24", "28", "56"], correctIndex: 2 },
  { id: 329, category: "quant", text: "A number is increased by 20% then decreased by 20%. What is the net percentage change?", options: ["0%", "−2%", "−4%", "+4%"], correctIndex: 2 },
  { id: 330, category: "quant", text: "The angles of a triangle are in ratio 2:3:7. What is the largest angle?", options: ["84°", "90°", "105°", "120°"], correctIndex: 2 },
  { id: 331, category: "quant", text: "Simplify: log(100) − log(10)  (base 10)", options: ["0", "1", "10", "90"], correctIndex: 1 },
  { id: 332, category: "quant", text: "A regular polygon's exterior angle is 24°. How many sides does it have?", options: ["12", "14", "15", "18"], correctIndex: 2 },
  { id: 333, category: "quant", text: "What is 3⁻² expressed as a fraction?", options: ["1/3", "1/6", "1/9", "−9"], correctIndex: 2 },
  { id: 334, category: "quant", text: "A rhombus has diagonals of 6 cm and 8 cm. What is its area?", options: ["18 cm²", "20 cm²", "24 cm²", "48 cm²"], correctIndex: 2 },
  { id: 335, category: "quant", text: "Two dice are rolled. What is the probability of getting a sum of 7?", options: ["1/9", "1/8", "1/6", "1/5"], correctIndex: 2 },
  { id: 336, category: "quant", text: "A shopkeeper has 250 kg of rice and sells 40% of it. How many kg remain?", options: ["100 kg", "120 kg", "150 kg", "160 kg"], correctIndex: 2 },
  { id: 337, category: "quant", text: "If P = {1,2,3,4} and Q = {3,4,5,6}, what is P ∩ Q?", options: ["{1,2}", "{3,4}", "{1,2,5,6}", "{1,2,3,4,5,6}"], correctIndex: 1 },
  { id: 338, category: "quant", text: "A factory produces 420 units in 7 days. How many units in 4 days?", options: ["200", "220", "240", "280"], correctIndex: 2 },
  { id: 339, category: "quant", text: "Find the midpoint of the segment joining (2, 4) and (8, 10):", options: ["(4, 6)", "(5, 6)", "(5, 7)", "(6, 7)"], correctIndex: 2 },
  { id: 340, category: "quant", text: "How many litres of a 40% acid solution must be mixed with 60 L of a 10% solution to get a 25% solution?", options: ["30", "40", "50", "60"], correctIndex: 3 },
  { id: 341, category: "quant", text: "A rectangle's length is three times its width. If its area is 192 cm², what is its length?", options: ["18 cm", "20 cm", "24 cm", "30 cm"], correctIndex: 2 },
  { id: 342, category: "quant", text: "If sin θ = 5/13, what is cos θ?", options: ["5/12", "12/13", "13/12", "5/13"], correctIndex: 1 },
  { id: 343, category: "quant", text: "The sum of the first n natural numbers is n(n+1)/2. What is the sum of the first 20 natural numbers?", options: ["190", "200", "210", "220"], correctIndex: 2 },
  { id: 344, category: "quant", text: "At 3:00, what is the angle between the hour and minute hands of a clock?", options: ["60°", "75°", "90°", "120°"], correctIndex: 2 },
  { id: 345, category: "quant", text: "What is the value of 0!?", options: ["0", "1", "Undefined", "∞"], correctIndex: 1 },
  { id: 346, category: "quant", text: "Two numbers have HCF 12 and LCM 180. If one number is 36, what is the other?", options: ["48", "54", "60", "72"], correctIndex: 2 },
  { id: 347, category: "quant", text: "If y = 3x − 5, what is x when y = 16?", options: ["5", "6", "7", "8"], correctIndex: 2 },
  { id: 348, category: "quant", text: "What is the remainder when 127 is divided by 8?", options: ["5", "6", "7", "8"], correctIndex: 2 },
  { id: 349, category: "quant", text: "A wire 120 cm long is bent into a rectangle whose length is twice its width. What is the area?", options: ["600 cm²", "700 cm²", "800 cm²", "1200 cm²"], correctIndex: 2 },
  { id: 350, category: "quant", text: "Express 45 as a product of prime factors:", options: ["2 × 3 × 5", "3² × 5", "5² × 3", "3 × 5²"], correctIndex: 1 },
  { id: 351, category: "quant", text: "What is the equation of a line with gradient 2 passing through (0, −3)?", options: ["y = 2x + 3", "y = 2x − 3", "y = −2x + 3", "y = −3x + 2"], correctIndex: 1 },
  { id: 352, category: "quant", text: "Evaluate: ∛64", options: ["2", "3", "4", "8"], correctIndex: 2 },
  { id: 353, category: "quant", text: "A bag contains 5 red, 3 blue, and 2 green balls. What is the probability of NOT drawing red?", options: ["1/3", "2/5", "1/2", "3/5"], correctIndex: 2 },
  { id: 354, category: "quant", text: "The mean of 6 numbers is 15. A 7th number is added and the new mean is 14. What is the 7th number?", options: ["6", "7", "8", "9"], correctIndex: 2 },
  { id: 355, category: "quant", text: "Find x: 16^x = 4", options: ["0.25", "0.5", "1", "2"], correctIndex: 1 },
  { id: 356, category: "quant", text: "A train 150 m long travelling at 72 km/h takes how long to cross a 300 m bridge?", options: ["18.0 s", "20.0 s", "22.5 s", "25.0 s"], correctIndex: 2 },
  { id: 357, category: "quant", text: "A farmer has 200 m of fencing. One side is a river (no fence needed). What is the maximum rectangular area?", options: ["4500 m²", "4800 m²", "5000 m²", "6000 m²"], correctIndex: 2 },
  { id: 358, category: "quant", text: "A shopkeeper mixes 20 kg of tea at $15/kg with 30 kg at $20/kg. What is the average price per kg?", options: ["$16", "$17", "$18", "$19"], correctIndex: 2 },
  { id: 359, category: "quant", text: "The 10th term of a geometric progression with first term 3 and common ratio 2 is:", options: ["512", "768", "1024", "1536"], correctIndex: 3 },
  { id: 360, category: "quant", text: "The ratio of areas of two similar triangles is 9:25. What is the ratio of their perimeters?", options: ["3:5", "9:25", "27:125", "√3:√5"], correctIndex: 0 },
  { id: 361, category: "quant", text: "A man scores 80, 75, 90, and 65 in four tests. What score is needed on the 5th to average 80?", options: ["85", "88", "90", "95"], correctIndex: 2 },
  { id: 362, category: "quant", text: "Solve: 2^(x+1) = 32", options: ["3", "4", "5", "6"], correctIndex: 1 },
  { id: 363, category: "quant", text: "What is the perimeter of a semicircle with diameter 14 cm? (π ≈ 22/7)", options: ["30 cm", "33 cm", "36 cm", "42 cm"], correctIndex: 2 },
  { id: 364, category: "quant", text: "If P(A) = 2/3 and P(B|A) = 1/4, what is P(A and B)?", options: ["1/8", "1/6", "1/4", "5/12"], correctIndex: 1 },
  { id: 365, category: "quant", text: "Find the distance between points (1, 2) and (4, 6):", options: ["4", "5", "6", "7"], correctIndex: 1 },
  { id: 366, category: "quant", text: "A man borrows $10,000 at 5% compound interest per year. How much does he owe after 2 years?", options: ["$10,500", "$11,000", "$11,025", "$11,250"], correctIndex: 2 },
  { id: 367, category: "quant", text: "How many ways can the letters of the word MATH be arranged?", options: ["12", "16", "24", "48"], correctIndex: 2 },
  { id: 368, category: "quant", text: "Find k if the mean of k, 2k, 3k, 4k is 15:", options: ["4", "5", "6", "8"], correctIndex: 2 },
  { id: 369, category: "quant", text: "A map has a scale of 1:50,000. A road is 8 cm on the map. How long is it in km?", options: ["2 km", "3 km", "4 km", "5 km"], correctIndex: 2 },
  { id: 370, category: "quant", text: "What is the area of an equilateral triangle with side 6 cm?", options: ["9 cm²", "9√3 cm²", "12 cm²", "12√3 cm²"], correctIndex: 1 },
  { id: 371, category: "quant", text: "What is the value of tan 45°?", options: ["0", "1/√2", "1", "√3"], correctIndex: 2 },
  { id: 372, category: "quant", text: "In a group of 50, 30 speak English and 25 speak French. If all speak at least one language, how many speak both?", options: ["3", "4", "5", "8"], correctIndex: 2 },
  { id: 373, category: "quant", text: "What is 3² × 2³?", options: ["48", "64", "72", "96"], correctIndex: 2 },
  { id: 374, category: "quant", text: "Find the sum of all even numbers from 2 to 100:", options: ["2450", "2500", "2550", "2600"], correctIndex: 2 },
  { id: 375, category: "quant", text: "What is the area of a parallelogram with base 12 cm and height 8 cm?", options: ["60 cm²", "80 cm²", "96 cm²", "100 cm²"], correctIndex: 2 },
  { id: 376, category: "quant", text: "If p% of 400 is 80, find p:", options: ["15", "18", "20", "25"], correctIndex: 2 },
  { id: 377, category: "quant", text: "A train goes at 60 km/h and a car at 90 km/h from the same point in the same direction. How far apart after 2 hours?", options: ["30 km", "45 km", "60 km", "75 km"], correctIndex: 2 },
  { id: 378, category: "quant", text: "What is the volume of a cuboid with length 5 cm, width 4 cm, and height 3 cm?", options: ["48 cm³", "55 cm³", "60 cm³", "65 cm³"], correctIndex: 2 },
  { id: 379, category: "quant", text: "A car depreciates at 15% per year. If its current value is $20,000, what will it be worth after 2 years?", options: ["$13,500", "$14,000", "$14,450", "$15,000"], correctIndex: 2 },
  { id: 380, category: "quant", text: "What is the equation of a circle with centre (0,0) and radius 5?", options: ["x² + y² = 5", "x² + y² = 25", "x + y = 5", "x² − y² = 25"], correctIndex: 1 },
  { id: 381, category: "quant", text: "If 2x + y = 10 and x − y = 2, what is x + y?", options: ["4", "5", "6", "8"], correctIndex: 2 },
  { id: 382, category: "quant", text: "What is the remainder when x² + 3x − 5 is divided by (x − 2)?", options: ["3", "4", "5", "6"], correctIndex: 2 },
  { id: 383, category: "quant", text: "How much water must be added to 10 litres of a 60% solution to dilute it to 40%?", options: ["3 L", "4 L", "5 L", "6 L"], correctIndex: 2 },
  { id: 384, category: "quant", text: "A sector of a circle has area 77 cm² and radius 7 cm. What is the sector angle? (π ≈ 22/7)", options: ["90°", "120°", "150°", "180°"], correctIndex: 3 },
  { id: 385, category: "quant", text: "What is the sum of all integers from 1 to 50?", options: ["1200", "1225", "1250", "1275"], correctIndex: 3 },
  { id: 386, category: "quant", text: "A box has 8 red and 5 blue balls. Two are drawn without replacement. What is P(both red)?", options: ["4/13", "14/39", "7/26", "8/13"], correctIndex: 1 },
  { id: 387, category: "quant", text: "Evaluate using BODMAS: 5 × 3 + 4² ÷ 2 − 1", options: ["20", "21", "22", "23"], correctIndex: 2 },
  { id: 388, category: "quant", text: "Express 2.4 × 10⁻³ as a decimal:", options: ["0.00024", "0.0024", "0.024", "0.24"], correctIndex: 1 },
  { id: 389, category: "quant", text: "A rhombus has a side of 13 cm and one diagonal of 10 cm. What is the length of the other diagonal?", options: ["20 cm", "22 cm", "24 cm", "26 cm"], correctIndex: 2 },
  { id: 390, category: "quant", text: "Two students complete a project in 6 hours. How long would it take 3 students at the same rate?", options: ["3 hours", "4 hours", "5 hours", "6 hours"], correctIndex: 1 },
  { id: 391, category: "quant", text: "What is the variance of: 55, 60, 70, 80, 85?", options: ["110", "120", "130", "140"], correctIndex: 2 },
  { id: 392, category: "quant", text: "Simplify: (1 + 1/x) ÷ (1 − 1/x) where x ≠ 0, 1", options: ["x + 1", "(x+1)/(x−1)", "(x−1)/(x+1)", "1"], correctIndex: 1 },
  { id: 393, category: "quant", text: "Express 0.333… as a fraction:", options: ["1/4", "1/3", "3/10", "33/100"], correctIndex: 1 },
  { id: 394, category: "quant", text: "Find the value of: 7² − 3²", options: ["36", "38", "40", "44"], correctIndex: 2 },
  { id: 395, category: "quant", text: "Solve: x² − 9 = 0", options: ["x = 3 only", "x = −3 only", "x = ±3", "x = ±9"], correctIndex: 2 },
  { id: 396, category: "quant", text: "A polygon has interior angles summing to 900°. How many sides does it have?", options: ["5", "6", "7", "8"], correctIndex: 2 },
  { id: 397, category: "quant", text: "What is √(3² + 4²)?", options: ["4", "5", "6", "7"], correctIndex: 1 },
  { id: 398, category: "quant", text: "How many 3-digit numbers are divisible by 7?", options: ["126", "127", "128", "129"], correctIndex: 2 },
  { id: 399, category: "quant", text: "Evaluate: 100C98", options: ["100", "4950", "9900", "9800"], correctIndex: 1 },
  { id: 400, category: "quant", text: "What is the value of log₂(1)?", options: ["0", "1", "2", "Undefined"], correctIndex: 0 },
];

function fisherYates<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function pickQuestions(count: number, pool: ScholarQuestion[]): ScholarQuestion[] {
  return fisherYates(pool).slice(0, count);
}

export function stripAnswers(q: ScholarQuestion): Omit<ScholarQuestion, "correctIndex"> {
  const { correctIndex: _c, ...rest } = q;
  return rest;
}
