// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tsia-marketplace/Marketplace.tsx": () => import("../components/mockups/tsia-marketplace/Marketplace.tsx")
};
