import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Bot, ShieldAlert, TrendingUp } from "lucide-react";

export default function BotLiveView() {
  const { data, isLoading } = useQuery<any>({ queryKey: ["/api/trade/bot-position"], refetchInterval: 10000 });
  const override = useMutation({ mutationFn: (action:string) => apiRequest("POST", "/api/trade/bot-position/override", { action }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/trade/bot-position"] }) });
  if (isLoading) return <div className="h-72 animate-pulse rounded-2xl bg-muted/50" />;
  if (!data?.active) return <div className="rounded-2xl border border-dashed p-10 text-center"><Bot className="mx-auto mb-3 h-10 w-10 text-muted-foreground" /><h2 className="font-black">Bot is offline</h2><p className="mt-1 text-sm text-muted-foreground">Your Itera session will appear here when active.</p></div>;
  return <div className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/5 p-5 shadow-xl backdrop-blur-xl"><div className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-muted-foreground">Live position</p><h2 className="mt-1 text-2xl font-black">{data.symbol} <span className="text-sm text-tsia-green">LONG</span></h2></div><TrendingUp className="h-6 w-6 text-tsia-green" /></div><div className="mt-7 grid grid-cols-2 gap-4 text-sm"><div><span className="text-xs text-muted-foreground">Entry</span><b className="block">${Number(data.entryPrice).toLocaleString()}</b></div><div><span className="text-xs text-muted-foreground">Unrealized P&L</span><b className="block text-tsia-green">+${Number(data.unrealizedPnl).toFixed(2)}</b></div></div><div className="mt-6 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-tsia-green" style={{width:`${Math.min(100,data.elapsedHours/12*100)}%`}} /></div><p className="mt-2 text-xs text-muted-foreground">{Number(data.elapsedHours).toFixed(1)}h into 12h session</p></div><div className="flex gap-2">{["close_early","double_down","reverse"].map(a=><button key={a} onClick={()=>{if(window.confirm(`Confirm ${a.replace("_"," ")}?`)) override.mutate(a)}} className="flex-1 rounded-xl border border-white/10 bg-white/5 px-2 py-3 text-[11px] font-bold">{a.replace("_"," ")}</button>)}</div><div className="flex items-center gap-2 rounded-xl bg-rose-400/10 p-3 text-xs text-rose-300"><ShieldAlert className="h-4 w-4"/> You may lose money. Override at your own risk.</div></div>;
}