import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Clock3, Radar } from "lucide-react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";

export default function TradingSignals({ tradeBalance }: { tradeBalance: number }) {
  const [amount, setAmount] = useState("10"); const [selected, setSelected] = useState<any>(null); const [hidden, setHidden] = useState<string[]>([]);
  const { data: signals = [], isLoading } = useQuery<any[]>({ queryKey: ["/api/trade/signals"], refetchInterval: 30000 });
  const { data: history = [] } = useQuery<any[]>({ queryKey: ["/api/trade/signals/history"], refetchInterval: 30000 });
  const enter = useMutation({ mutationFn: () => apiRequest("POST", "/api/trade/signals/enter", { ...selected, amountUsd: Number(amount) }), onSuccess: () => { setSelected(null); queryClient.invalidateQueries({ queryKey: ["/api/trade/wallet"] }); queryClient.invalidateQueries({ queryKey: ["/api/trade/signals/history"] }); } });
  return <div className="space-y-5">
    <header><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-tsia-green"><Radar className="h-4 w-4" /> Itera signal desk</div><h2 className="mt-2 text-2xl font-black">Trade the moment.</h2><p className="text-sm text-muted-foreground">Live setups, measured risk, no guesswork.</p></header>
    <div className="grid gap-3">{isLoading ? [1,2,3].map(i => <div key={i} className="h-48 animate-pulse rounded-2xl bg-muted/50" />) : signals.filter((s:any) => !hidden.includes(s.id)).map((s:any, i:number) => <SignalCard key={s.id} signal={s} index={i} onEnter={() => setSelected(s)} onSkip={() => setHidden(x => [...x, s.id])} />)}</div>
    {!isLoading && !signals.length && <div className="rounded-2xl border border-dashed p-10 text-center"><Radar className="mx-auto mb-3 h-10 w-10 text-tsia-green/60" /><p className="font-bold">No signals right now</p><p className="mt-1 text-xs text-muted-foreground">The desk is scanning fresh market data.</p></div>}
    <section className="rounded-2xl border border-white/10 bg-white/5 p-4 shadow-xl backdrop-blur-xl"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">Recent signal trades</h3><span className="text-xs text-muted-foreground">Balance ${tradeBalance.toFixed(2)}</span></div>{history.slice(0,10).map((t:any) => <div key={t.id} className="flex items-center justify-between border-t border-white/10 py-3 text-xs"><span className="font-bold">{t.symbol} <em className={t.direction === "long" ? "text-tsia-green" : "text-rose-400"}>{t.direction}</em></span><span>${Number(t.amountUsd).toFixed(2)}</span><b className={Number(t.pnlUsd) >= 0 ? "text-tsia-green" : "text-rose-400"}>{t.pnlUsd == null ? "OPEN" : `${Number(t.pnlUsd) >= 0 ? "+" : ""}$${Number(t.pnlUsd).toFixed(2)}`}</b></div>)}</section>
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4 backdrop-blur-sm"><div className="w-full max-w-sm rounded-2xl border border-white/15 bg-slate-900 p-5 shadow-2xl"><h3 className="text-lg font-black">Enter {selected.symbol}</h3><p className="mt-1 text-sm text-muted-foreground">{selected.direction.toUpperCase()} at ${Number(selected.entryPrice).toLocaleString()}</p><label className="mt-5 block text-xs font-bold uppercase text-muted-foreground">Amount (USD)<input autoFocus type="number" min="1" max={tradeBalance} value={amount} onChange={e => setAmount(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/10 p-3 text-lg outline-none" /></label><div className="mt-5 flex gap-2"><button onClick={() => setSelected(null)} className="flex-1 rounded-xl border border-white/10 p-3 text-sm">Cancel</button><button disabled={enter.isPending || Number(amount) < 1 || Number(amount) > tradeBalance} onClick={() => enter.mutate()} className="flex-1 rounded-xl bg-tsia-green p-3 text-sm font-bold text-white disabled:opacity-40">{enter.isPending ? "Opening…" : "Confirm trade"}</button></div></div></div>}
  </div>;
}
function SignalCard({ signal:s, index, onEnter, onSkip }: any) { const [left, setLeft] = useState(Math.max(0, Math.floor((new Date(s.expiresAt).getTime()-Date.now())/1000))); useEffect(() => { const t=setInterval(()=>setLeft(Math.max(0,Math.floor((new Date(s.expiresAt).getTime()-Date.now())/1000))),1000); return()=>clearInterval(t); },[s.expiresAt]); const long=s.direction==="long"; return <motion.article initial={{ opacity:0,y:12 }} animate={{ opacity:1,y:0 }} transition={{ delay:index*.07 }} className="rounded-2xl border border-white/10 bg-white/5 p-4 shadow-xl backdrop-blur-xl"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 font-black">{s.symbol}<span className="text-xs font-medium text-muted-foreground">{s.label}</span></div><span className={`mt-2 inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-black ${long?"bg-tsia-green/15 text-tsia-green":"bg-rose-400/15 text-rose-400"}`}>{long?<ArrowUpRight className="h-3 w-3"/>:<ArrowDownRight className="h-3 w-3"/>}{s.direction.toUpperCase()}</span></div><div className="text-right text-xs text-muted-foreground"><Clock3 className="ml-auto mb-1 h-4 w-4"/>{Math.floor(left/60)}:{String(left%60).padStart(2,"0")}</div></div><div className="mt-5 flex justify-between text-xs"><span>Confidence <b>{s.confidence}%</b></span><span>Entry <b>${Number(s.entryPrice).toLocaleString()}</b></span></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><motion.div animate={{ width:`${s.confidence}%` }} className={`h-full rounded-full ${s.confidence>80?"bg-tsia-green":"bg-tsia-gold"}`}/></div><div className="mt-4 flex gap-2"><button onClick={onEnter} className="flex-1 rounded-xl bg-tsia-green py-2.5 text-xs font-bold text-white">Enter Trade</button><button onClick={onSkip} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs">Skip</button></div></motion.article>; }